version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Davidwagih123
      POSTGES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - shared-network
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    container_name: swe-project-container
    restart: unless-stopped
    image: swe-project-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  shared-network:
