version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Davidwagih123
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  our-app:
    image: my-app:latest
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: our-app
    depends_on:
      - postgres
      - pgadmin
    ports:
      - "3000:3000"
    restart: always
volumes:
  postgres-data:
  pgadmin-data:

networks:
  shared-network:
